services:
  postgres:
    image: postgres:15
    container_name: quarkus_postgres
    restart: always
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: quarkus_password
      POSTGRES_DB: inventario_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quarkus-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus_user -d inventario_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  app:
    build:
      context: .
      dockerfile: Dockerfile-java
    container_name: quarkus_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/inventario_db
      QUARKUS_DATASOURCE_USERNAME: quarkus_user
      QUARKUS_DATASOURCE_PASSWORD: quarkus_password
    volumes:
      - ./privateKey.pem:/app/privateKey.pem
    networks:
      - quarkus-net

networks:
  quarkus-net:
    driver: bridge

volumes:
  postgres_data:
